FROM python:3.10.6

RUN pip install pipenv pytest 

WORKDIR /app

COPY Pipfile Pipfile.lock /app/

RUN pipenv install --system --deploy

COPY . /app



RUN cd ./src/
WORKDIR /app/src
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0" ]
